// <auto-generated />
using System;
using LearnNN_WebBlazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnNN_WebBlazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008192349_AddPersonalizationCoreAndSrs")]
    partial class AddPersonalizationCoreAndSrs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.AnswerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAnswer")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SkillTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("SkillTagId");

                    b.HasIndex("ItemType", "ItemId");

                    b.ToTable("AnswerLogs");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.LearnerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("DailyGoalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExamDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredAccent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetScore")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LearnerProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentStage = "S1",
                            DailyGoalMinutes = 30,
                            PreferredAccent = "en-US",
                            TargetScore = 650
                        });
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.SkillTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("SkillTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Vocabulary",
                            Code = "VOC.ROOT",
                            Name = "Từ vựng tổng quát"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Grammar",
                            Code = "GRAM.ROOT",
                            Name = "Ngữ pháp tổng quát"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Listening",
                            Code = "LIS.ROOT",
                            Name = "Kỹ năng nghe"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Reading",
                            Code = "READ.ROOT",
                            Name = "Kỹ năng đọc"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Vocabulary",
                            Code = "VOC.TOEIC_600",
                            Name = "Từ vựng TOEIC 600 Essential Words",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Vocabulary",
                            Code = "VOC.WORD_FORM",
                            Name = "Cấu tạo từ & Từ loại (Word Form)",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Vocabulary",
                            Code = "VOC.COLLOCATION",
                            Name = "Cụm từ đi kèm (Collocation)",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "Grammar",
                            Code = "GRAM.TENSE",
                            Name = "Các thì trong tiếng Anh",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 9,
                            Category = "Grammar",
                            Code = "GRAM.PARTS_OF_SPEECH",
                            Name = "Từ loại & Vị trí trong câu",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = "Grammar",
                            Code = "GRAM.PASSIVE_VOICE",
                            Name = "Câu bị động",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 11,
                            Category = "Grammar",
                            Code = "GRAM.RELATIVE_CLAUSE",
                            Name = "Mệnh đề quan hệ",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 12,
                            Category = "Listening",
                            Code = "LIS.PART1_PHOTO",
                            Name = "Part 1 - Mô tả hình ảnh",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 13,
                            Category = "Listening",
                            Code = "LIS.PART2_QA",
                            Name = "Part 2 - Hỏi đáp",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 14,
                            Category = "Listening",
                            Code = "LIS.PART3_CONV",
                            Name = "Part 3 - Đoạn hội thoại",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 15,
                            Category = "Listening",
                            Code = "LIS.PART4_TALK",
                            Name = "Part 4 - Bài nói ngắn",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 16,
                            Category = "Reading",
                            Code = "READ.PART5_INCOMPLETE",
                            Name = "Part 5 - Điền câu",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 17,
                            Category = "Reading",
                            Code = "READ.PART6_TEXT_COMPLETION",
                            Name = "Part 6 - Hoàn thành đoạn văn",
                            ParentId = 4
                        },
                        new
                        {
                            Id = 18,
                            Category = "Reading",
                            Code = "READ.PART7_SINGLE_PASSAGE",
                            Name = "Part 7 - Đoạn đơn",
                            ParentId = 4
                        });
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.TagMastery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPracticedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MasteryScore")
                        .HasColumnType("REAL");

                    b.Property<int>("SkillTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkillTagId");

                    b.ToTable("TagMasteries");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Từ vựng về công nghệ thông tin, lập trình, phần mềm",
                            Name = "Công nghệ"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Từ vựng giao tiếp hàng ngày, xã giao, văn phòng",
                            Name = "Giao tiếp"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Từ vựng học thuật dùng trong kỳ thi IELTS",
                            Name = "IELTS Academic"
                        });
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleTranslation")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMastered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsMastered");

                    b.HasIndex("Term");

                    b.HasIndex("TopicId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "The sorting algorithm runs in O(n log n) time.",
                            ExampleTranslation = "Thuật toán sắp xếp này chạy trong thời gian O(n log n).",
                            IsMastered = false,
                            Meaning = "Thuật toán – tập hợp các bước xử lý để giải quyết bài toán",
                            PartOfSpeech = "noun",
                            Phonetic = "/ˈæl.ɡə.rɪ.ðəm/",
                            Term = "algorithm",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = ".NET is a powerful framework for building web applications.",
                            ExampleTranslation = ".NET là một framework mạnh mẽ để xây dựng ứng dụng web.",
                            IsMastered = false,
                            Meaning = "Khung phần mềm – bộ thư viện/công cụ hỗ trợ xây dựng ứng dụng",
                            PartOfSpeech = "noun",
                            Phonetic = "/ˈfreɪm.wɜːk/",
                            Term = "framework",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "Please push your code to the Git repository.",
                            ExampleTranslation = "Hãy đẩy code của bạn lên kho Git.",
                            IsMastered = false,
                            Meaning = "Kho lưu trữ mã nguồn",
                            PartOfSpeech = "noun",
                            Phonetic = "/rɪˈpɒz.ɪ.tər.i/",
                            Term = "repository",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "I apologize for the delay in responding.",
                            ExampleTranslation = "Tôi xin lỗi vì đã trả lời trễ.",
                            IsMastered = false,
                            Meaning = "Xin lỗi, tạ lỗi",
                            PartOfSpeech = "verb",
                            Phonetic = "/əˈpɒl.ə.dʒaɪz/",
                            Term = "apologize",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "Could you clarify what you mean by that?",
                            ExampleTranslation = "Bạn có thể làm rõ ý bạn muốn nói không?",
                            IsMastered = false,
                            Meaning = "Làm rõ, giải thích rõ hơn",
                            PartOfSpeech = "verb",
                            Phonetic = "/ˈklær.ɪ.faɪ/",
                            Term = "clarify",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "There has been a substantial increase in online learning.",
                            ExampleTranslation = "Đã có sự gia tăng đáng kể trong việc học trực tuyến.",
                            IsMastered = false,
                            Meaning = "Đáng kể, quan trọng, lớn về quy mô",
                            PartOfSpeech = "adjective",
                            Phonetic = "/səbˈstæn.ʃəl/",
                            Term = "substantial",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "The task was difficult; nonetheless, she completed it.",
                            ExampleTranslation = "Nhiệm vụ rất khó; dẫu vậy, cô ấy đã hoàn thành nó.",
                            IsMastered = false,
                            Meaning = "Tuy nhiên, dẫu vậy, mặc dù thế",
                            PartOfSpeech = "adverb",
                            Phonetic = "/ˌnʌn.ðəˈles/",
                            Term = "nonetheless",
                            TopicId = 3
                        });
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.WordProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("EaseFactor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(2.5);

                    b.Property<int>("IntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("Lapses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastStudiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Repetitions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("WordId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("WordId")
                        .IsUnique();

                    b.ToTable("WordProgresses");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.AnswerLog", b =>
                {
                    b.HasOne("LearnNN_WebBlazor.Data.Entities.SkillTag", "SkillTag")
                        .WithMany("AnswerLogs")
                        .HasForeignKey("SkillTagId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SkillTag");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.SkillTag", b =>
                {
                    b.HasOne("LearnNN_WebBlazor.Data.Entities.SkillTag", "ParentTag")
                        .WithMany("ChildTags")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.TagMastery", b =>
                {
                    b.HasOne("LearnNN_WebBlazor.Data.Entities.SkillTag", "SkillTag")
                        .WithMany("TagMasteries")
                        .HasForeignKey("SkillTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillTag");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Word", b =>
                {
                    b.HasOne("LearnNN_WebBlazor.Data.Entities.Topic", "Topic")
                        .WithMany("Words")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.WordProgress", b =>
                {
                    b.HasOne("LearnNN_WebBlazor.Data.Entities.Word", "Word")
                        .WithOne("WordProgress")
                        .HasForeignKey("LearnNN_WebBlazor.Data.Entities.WordProgress", "WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.SkillTag", b =>
                {
                    b.Navigation("AnswerLogs");

                    b.Navigation("ChildTags");

                    b.Navigation("TagMasteries");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Topic", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Word", b =>
                {
                    b.Navigation("WordProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
