// <auto-generated />
using System;
using LearnNN_WebBlazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnNN_WebBlazor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260922154304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Từ vựng về công nghệ thông tin, lập trình, phần mềm",
                            Name = "Công nghệ"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Từ vựng giao tiếp hàng ngày, xã giao, văn phòng",
                            Name = "Giao tiếp"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Từ vựng học thuật dùng trong kỳ thi IELTS",
                            Name = "IELTS Academic"
                        });
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("ExampleSentence")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExampleTranslation")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMastered")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsMastered");

                    b.HasIndex("Term");

                    b.HasIndex("TopicId");

                    b.ToTable("Words");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "The sorting algorithm runs in O(n log n) time.",
                            ExampleTranslation = "Thuật toán sắp xếp này chạy trong thời gian O(n log n).",
                            IsMastered = false,
                            Meaning = "Thuật toán – tập hợp các bước xử lý để giải quyết bài toán",
                            PartOfSpeech = "noun",
                            Phonetic = "/ˈæl.ɡə.rɪ.ðəm/",
                            Term = "algorithm",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = ".NET is a powerful framework for building web applications.",
                            ExampleTranslation = ".NET là một framework mạnh mẽ để xây dựng ứng dụng web.",
                            IsMastered = true,
                            Meaning = "Khung phần mềm – bộ thư viện/công cụ hỗ trợ xây dựng ứng dụng",
                            PartOfSpeech = "noun",
                            Phonetic = "/ˈfreɪm.wɜːk/",
                            Term = "framework",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "Please push your code to the Git repository.",
                            ExampleTranslation = "Hãy đẩy code của bạn lên kho Git.",
                            IsMastered = false,
                            Meaning = "Kho lưu trữ mã nguồn",
                            PartOfSpeech = "noun",
                            Phonetic = "/rɪˈpɒz.ɪ.tər.i/",
                            Term = "repository",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "I apologize for the delay in responding.",
                            ExampleTranslation = "Tôi xin lỗi vì đã trả lời trễ.",
                            IsMastered = false,
                            Meaning = "Xin lỗi, tạ lỗi",
                            PartOfSpeech = "verb",
                            Phonetic = "/əˈpɒl.ə.dʒaɪz/",
                            Term = "apologize",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "Could you clarify what you mean by that?",
                            ExampleTranslation = "Bạn có thể làm rõ ý bạn muốn nói không?",
                            IsMastered = true,
                            Meaning = "Làm rõ, giải thích rõ hơn",
                            PartOfSpeech = "verb",
                            Phonetic = "/ˈklær.ɪ.faɪ/",
                            Term = "clarify",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "There has been a substantial increase in online learning.",
                            ExampleTranslation = "Đã có sự gia tăng đáng kể trong việc học trực tuyến.",
                            IsMastered = false,
                            Meaning = "Đáng kể, quan trọng, lớn về quy mô",
                            PartOfSpeech = "adjective",
                            Phonetic = "/səbˈstæn.ʃəl/",
                            Term = "substantial",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExampleSentence = "The task was difficult; nonetheless, she completed it.",
                            ExampleTranslation = "Nhiệm vụ rất khó; dẫu vậy, cô ấy đã hoàn thành nó.",
                            IsMastered = false,
                            Meaning = "Tuy nhiên, dẫu vậy, mặc dù thế",
                            PartOfSpeech = "adverb",
                            Phonetic = "/ˌnʌn.ðəˈles/",
                            Term = "nonetheless",
                            TopicId = 3
                        });
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Word", b =>
                {
                    b.HasOne("LearnNN_WebBlazor.Data.Entities.Topic", "Topic")
                        .WithMany("Words")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearnNN_WebBlazor.Data.Entities.Topic", b =>
                {
                    b.Navigation("Words");
                });
#pragma warning restore 612, 618
        }
    }
}
